### ISSUE TITLE
[BUG] Streamdeck XL not working with current 2.2.0 builds (Win10)

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion#1337]
**Describe the bug**
Streamdeck XL only shows the Streamdeck logo with the current builds (I've tried several)
Also tried it on 2 different PC's both running Win10 2004

It still works fine with the 2.1.2 release and the web interface works as usual.
Also the regular Stream Deck app works fine. 

Rescanning USB doesn't help.

Anyone else experiencing this issue?

P.S.: The log:
`21. 15:38:35 instance(countdown): Network error: connect ECONNREFUSED 2.39.2.17:61002
21. 15:38:26 module(openweather-rest): Error loading module: Error: Cannot find module 'sharp' Require stack: - C:\Program Files\Companion\resources\app.asar\lib\module\openweather-rest\index.js - C:\Program Files\Companion\resources\app.asar\lib\instance.js - C:\Program Files\Companion\resources\app.asar\app.js - C:\Program Files\Companion\resources\app.asar\electron.js -
21. 15:38:25 module(haivision-connectdvr): Error loading module: Error: Cannot find module 'sharp' Require stack: - C:\Program Files\Companion\resources\app.asar\lib\module\haivision-connectdvr\index.js - C:\Program Files\Companion\resources\app.asar\lib\instance.js - C:\Program Files\Companion\resources\app.asar\app.js - C:\Program Files\Companion\resources\app.asar\electron.js -`

**Comment by stevespaw** [comment]
Yes I have the exact same problem, the last working version is 2703 for me.

**Comment by Julusian** [comment]
Yeah, this is known and something I am looking into.
The 2.2.0 builds are rather buggy currently

**Comment by Julusian** [comment]
I think that build 2747 should fix this. Could someone test and report back?

**Comment by stevespaw** [comment]
Streamdeck is alive on Win64 !
Thanks,
Merry Christmas!

Will try ubuntu later
