### ISSUE TITLE
Cannot load ATEM module after upgrade to 2.2.0 b3558

### ISSUE THREAD

**Issue by joshuachung** [bitfocus/companion#1747]
Here is the log:

21.10.05 12:23:40 module(bmd-atem): Error loading module: Error: Cannot find module '/Applications/Companion 2.2.0 b3558.app/Contents/Resources/app.asar/node_modules/companion-module-bmd-atem/dist/index.js' Require stack: - /Applications/Companion 2.2.0 b3558.app/Contents/Resources/app.asar/lib/instance.js - /Applications/Companion 2.2.0 b3558.app/Contents/Resources/app.asar/app.js - /Applications/Companion 2.2.0 b3558.app/Contents/Resources/app.asar/electron.js -

**Comment by CallenMagnuson** [comment]
I have installed several recent beta builds on multiple computers including one that has never had Companion installed. Builds 3609 and 3614 are ones I can confirm I've installed.

I am getting the same error listed above when trying to use or add the ATEM module.

**Comment by Julusian** [comment]
@CallenMagnuson what os are you trying on?

**Comment by CallenMagnuson** [comment]
> @CallenMagnuson what os are you trying on?

Apologies. This is on both Windows 10 and Windows 11.

**Comment by Julusian** [comment]
That is interesting, because the bmd-atem module appears to work in 3609, but not the behringer-x32.
I'm adding a check to the build process, to detect this scenario and to fail to produce a build instead of an incomplete one.
Hopefully this will give some more insight into where the problem is occuring, so that we can fix it

**Comment by Julusian** [comment]
I think I have fixed the underlying problem now
